CREATE DATABASE IF NOT EXISTS cafe_management
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_unicode_ci;

USE cafe_management;

CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
